DROP DATABASE IF EXISTS  LibraSphereDB;
CREATE DATABASE IF NOT EXISTS LibraSphereDB;
USE LibraSphereDB;

CREATE TABLE Empleado (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    DNI VARCHAR (15) NOT NULL ,
    Nombre VARCHAR(100) NOT NULL,
    Edad INT NOT NULL,
    Email VARCHAR(150) NOT NULL,
    Contrasena VARCHAR(200) NOT NULL,
    NivelPermiso INT NOT NULL
);

