DROP DATABASE IF EXISTS  LibraSphereDB;
CREATE DATABASE IF NOT EXISTS LibraSphereDB;
USE LibraSphereDB;

CREATE TABLE IF NOT EXISTS Empleado (
    IdEmpleado INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Edad INT NOT NULL,
    Email VARCHAR(150) NOT NULL,
    Contrasena VARCHAR(200) NOT NULL,
    NivelPermiso INT NOT NULL
);

